apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/apps/*
      # - ./infra/k8s-local/*
build:
  local:
    push: false
  artifacts:
    - image: fhuadeen/producer-dag
      context: cluster_workflow
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "***/*.py"
            dest: .