apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-depl
spec:
  selector:
    matchLabels:
      app: data-producer
  template:
    metadata:
      labels:
        app: data-producer
    spec:
      containers:
        - name: data-producer
          image: fhuadeen/tweet_data_producer
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 4500

---
apiVersion: v1
kind: Service
metadata:
  name: data-producer-srv
spec:
  selector:
    app: data-producer
  ports:
    - name: data-producer
      protocol: TCP
      port: 4500
      targetPort: 4500
